# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2025 Intel Corporation
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: omec-project/.github/.github/workflows/build.yml@main
    with:
      branch_name: ${{ github.ref }}

  build-dbtestapp:
    uses: omec-project/.github/.github/workflows/build.yml@main
    with:
      branch_name: ${{ github.ref }}
      build_directory: mongoapi/dbtestapp

  docker-build-dbtestapp:
    uses: omec-project/.github/.github/workflows/docker-build.yml@main
    with:
      branch_name: ${{ github.ref }}
      build_directory: mongoapi/dbtestapp

  static-analysis:
    uses: omec-project/.github/.github/workflows/static-analysis.yml@main
    with:
      branch_name: ${{ github.ref }}

  lint:
    uses: omec-project/.github/.github/workflows/lint.yml@main
    with:
      branch_name: ${{ github.ref }}

  lint-dbtestapp:
    uses: omec-project/.github/.github/workflows/lint.yml@main
    with:
      branch_name: ${{ github.ref }}
      build_directory: ./mongoapi/dbtestapp

  license-check:
    uses: omec-project/.github/.github/workflows/license-check.yml@main
    with:
      branch_name: ${{ github.ref }}

  fossa-scan:
    uses: omec-project/.github/.github/workflows/fossa-scan.yml@main
    with:
      branch_name: ${{ github.ref }}

  unit-tests:
    uses: omec-project/.github/.github/workflows/unit-test.yml@main
    with:
      branch_name: ${{ github.ref }}
